# Generated by Django 2.2.1 on 2019-06-24 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_area', models.CharField(choices=[('domestic', 'Domestic'), ('international', 'International')], max_length=20, null=True)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('shipping_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendorpanel.ShippingType')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_option', to=settings.AUTH_USER_MODEL, verbose_name='Vendor ID')),
            ],
        ),
    ]
